apiVersion: v1
kind: Pod
metadata:
  name: $name
  labels:
    app: $name
spec:
  containers:
  - name: $name
    image: $image
    ports:
    - containerPort: $port
    env:
    - name: GITLAB_OMNIBUS_CONFIG
      value: $config
